# Generated by Django 3.0.3 on 2020-02-19 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='skills',
            field=models.CharField(default=[], max_length=100),
            preserve_default=False,
        ),
    ]
